version: '3'

services:
  db:
    image: mongodb:latest
    volumes:
      - db_data:/data/db
    restart: always

  payment_nodejs:
    depends_on:
      - db
    image: payment_nodejs:latest
    volumes:
      - app:/payment
    ports:
      - "9000:9000"
    restart: always


volumes:
  db_data:
  app:
